### ISSUE TITLE
Stop using our travis script

### ISSUE THREAD

**Issue by HimbeersaftLP** [XxParkerGamesxX/CellPE#1]
It's copyrighted by us and you don't even know how to use it, if you don't delete it immediately I will report this to GitHub

**Comment by XxParkerGamesxX** [comment]
For what lol

**Comment by HimbeersaftLP** [comment]
Hmm doesn't seem to work anymore right? https://travis-ci.org/XxParkerGamesxX/CellPE#L713

Muahwhahahaha
