### ISSUE TITLE
Bull shit, changes my title from Not yours to Love it, Fraud

### ISSUE THREAD

**Issue by DaPigGuy** [XxParkerGamesxX/CellPE#1]
Bull shit, changes my title from Not yours to Love it, Fraud. This isn't your plugin.

**Comment by XxParkerGamesxX** [comment]
ty

**Comment by DaPigGuy** [comment]
Wtf. Fraud...

**Comment by QuiverlyRivalry** [comment]
Go home Parker don't copy of someone else's work show us what you got? A brain might be good, or what do you rely on that copy and paste to do the thinking for you? your just a fraud a chest a sad boy who just wants to be noticed but newsflash copying will make you UNPOPULAR

**Comment by DaPigGuy** [comment]
Oink oink. Piggy agrees!

**Comment by QuiverlyRivalry** [comment]
Yeah whatever mrfraud, did your copy and paste break?

**Comment by Aericio** [comment]
brought to you by scriptkiddie identity protection
